


# You can now execute commands that use the credentials👇
#- name: Serverless deploy
#  run: sls deploy --stage dev

name: Sync to S3
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: ca-central-1 # use your region here.

      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync . s3://ola-cloud-resume --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ca-central-1
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       